# Conceal configuration file

title = "conceal.toml"
ver = "0.0.1"

[normalize]
width_all = 400
height_all = 400
width_one = 1000
height_one = 1000

[collage]
width = 400
height = 400

[palette]
colors = 8

[finalcolors]
amount = 6

[noise]
width = 500
height = 500
randomweight = 0.0
perlinweight = 0.7
simplexweight = 0.3

[perlin]
octaves = 7
frequency = 10.0 

[voronoi]
width = 500
height = 500
cells = 25