# Conceal configuration file

title = "conceal.toml"
ver = "0.0.1"

[files]
imagefolder = "img_set1_wa"
resultfolder = "results"
normalized = "img_set1_wa_normalized"
collage = "collage.png"
colors = "colors.png"
noise = "noise.png"
colorshift = "colorshift.png"
dither = "dither.png"
output = "voronoi.png"

[normalize]
width_all = 400
height_all = 400
width_one = 1000
height_one = 1000

[collage]
width = 400
height = 400

[colors]
palette = 16
noise = 10
dither = 6

[noise]
width = 500
height = 500
randomweight = 0.02
perlinweight = 0.4
simplexweight = 0.58

[perlin]
octaves = 10
frequency = 30.0 

[voronoi]
cells = 1000