# Conceal configuration file

title = "conceal.toml"
ver = "0.0.1"

[files]
imagefolder = "environment"
resultfolder = "results"
normalized = "env_norm"
collage = "collage.png"
colors = "colors.png"
noise = "noise.png"
colorshift = "colorshift.png"
dither = "dither.png"
output = "voronoi.png"

[normalize]
width_all = 400
height_all = 400
width_one = 1000
height_one = 1000

[collage]
width = 400
height = 400

[colors]
palette = 16
noise = 16
dither = 5

[noise]
width = 500
height = 500
randomweight = 0.00
perlinweight = 0.6
simplexweight = 0.4

[perlin]
octaves = 10
frequency = 15.0 

[voronoi]
cells = 3000
